#!/usr/bin/env python
#YODO 0.1.0

# # # # # # # # # # # # # # # # # # # # #
#	TODO
#
#	- https://trello.com/b/7cWRawLR/yodo
#
# # # # # # # # # # # # # # # # # # # # #

import os, sys, argparse, json

dev = True
current_dir = os.getcwd()
ver = '0.1.0'

if dev:
	import pprint
	print '--------------'
	print 'Dev stuff, nevermind...'
	print 'yoDo ver: \t\t' + ver
	print 'Sys: \t\t' + sys.platform
	sys.stdout.write('Args: \t\t')
	for arg in sys.argv:
		sys.stdout.write(arg)
	print
	print '--------------'
	settings = os.getcwd() + '/settings'
else:
	settings = os.getcwd() + '/.yodo/settings'

with open(settings) as settings_file:
	settings = json.load(settings_file)

sys.path.insert(0, settings['paths']['libs'])
sys.path.insert(0, settings['paths']['modules'])

from yoDo import Yodo

def main():
	yodo = Yodo(settings)
	yodo.do()

if __name__ == '__main__':
	main()